---
chromadb:
  remote: False
  persist_dir: "./persist.local"
  host: localhost
  port: 8080
  collection: "default"
  collection_similarity: "cosine"

training_data:
  sources:
    - data_type: "text"
      path: "/training_data"
      pattern: "**/*.txt"
    - data_type: "pdf"
      path: "/training_data"
      pattern: "**/*.pdf"
  chunk_size: 1000
  chunk_overlap: 0
  separator: "\n\n"
  language: "english"

llamaindex:
  data_path: "/data_path"
  extensions:
    - ".txt"
    - ".pdf"
  show_progress: True
  recursive: True

embeddings:
  local: True
  remote_service: "ollama"
  sentence_transformer:
    model: "all-MiniLM-L6-v2"
  ollama:
    baseurl: "http://localhost:11434"
    model: "nomic-embed-text:latest"
  openai:
    baseurl: "http://localhost:11434"
    model: "nomic-embed-text:latest"
    apikey: "your_api_key"
