---
chromadb:
  remote: False
  persist_dir: "./persist.local"
  host: localhost
  port: 8080
  collection: "default"
  collection_similarity: "cosine"

training_data:
  path: "/training_data"
  pattern: "**/*.txt"
  chunk_size: 1000
  chunk_overlap: 0
  separator: "\n\n"
  language: "english"

embeddings:
  local: True
  sentence_transformer:
    model: "all-MiniLM-L6-v2"
  ollama:
    baseurl: "http://localhost:11434"
    model: "nomic-embed-text:latest"
